export const SECTORS = [
  "Agriculture",
  "Agroalimentaire",
  "Automobile",
  "Aéronautique",
  "Banque",
  "Assurance",
  "Finance",
  "Comptabilité",
  "Audit & Conseil",
  "BTP",
  "Immobilier",
  "Architecture",
  "Industrie",
  "Production",
  "Énergie",
  "Mines",
  "Pétrole & Gaz",
  "Eau & Environnement",
  "Transport",
  "Logistique",
  "Supply Chain",
  "Maritime",
  "Ferroviaire",
  "Télécommunications",
  "Informatique",
  "Technologies de l'information",
  "Cybersécurité",
  "Intelligence Artificielle",
  "E-commerce",
  "Marketing",
  "Communication",
  "Publicité",
  "Médias",
  "Imprimerie",
  "Distribution",
  "Commerce",
  "Import/Export",
  "Luxe",
  "Textile",
  "Santé",
  "Pharmaceutique",
  "Cosmétique",
  "Biotechnologies",
  "Éducation",
  "Formation",
  "Collectivités Territoriales",
  "ONG/Associations",
  "Hôtellerie",
  "Restauration",
  "Centres d'appels/BPO",
  "Événementiel",
  "Services aux entreprises",
  "Sécurité",
  "Nettoyage industriel",
  "Facility Management",
  "Juridique",
  "Administration RH",
  "Recrutement",
  "Achats",
  "Qualité",
  "Maintenance",
  "Artisanat",
  "Électronique",
  "Électromécanique",
  "Chimie",
  "Plasturgie",
  "Bois & Papier",
  "Métallurgie",
  "Bureaux d'études",
  "Digital",
  "Start-up",
  "Holding",
  "Multi-secteurs",
  "Autre",
] as const;

export const EXPERIENCE_LEVELS = ["0–1 an", "2–5 ans", "5–10 ans", "10 ans et plus"] as const;

export const EDUCATION_LEVELS = [
  "Inférieur Bac",
  "Bac",
  "Bac+2",
  "Bac+3",
  "Bac+5",
  "Ingénieur",
  "Master",
  "Doctorat",
] as const;

export const CONTRACT_TYPES = ["CDI", "CDD", "Intérim", "Stage", "Freelance", "Alternance"] as const;
