"""user activation flow

Revision ID: 85ec75b0960b
Revises: 20260627_interview_eval_pipeline
Create Date: 2026-06-30 00:27:23.360619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85ec75b0960b'
down_revision: Union[str, None] = '20260627_interview_eval_pipeline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _columns(table_name: str) -> set[str]:
    return {column["name"] for column in sa.inspect(op.get_bind()).get_columns(table_name)}


def _indexes(table_name: str) -> set[str]:
    return {index["name"] for index in sa.inspect(op.get_bind()).get_indexes(table_name)}


def _unique_constraints(table_name: str) -> set[str]:
    return {
        constraint["name"]
        for constraint in sa.inspect(op.get_bind()).get_unique_constraints(table_name)
        if constraint["name"]
    }


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evaluations', 'recommendation',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.alter_column('interviews', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.alter_column('job_offers', 'soft_skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('job_offers', 'languages',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    if 'system_settings_key_key' in _unique_constraints('system_settings'):
        op.drop_constraint('system_settings_key_key', 'system_settings', type_='unique')

    user_columns = _columns('users')
    if 'activation_token' not in user_columns:
        op.add_column('users', sa.Column('activation_token', sa.String(length=255), nullable=True))
    if 'token_expires_at' not in user_columns:
        op.add_column('users', sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True))

    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               nullable=True)
    if 'ix_users_activation_token' not in _indexes('users'):
        op.create_index(op.f('ix_users_activation_token'), 'users', ['activation_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if 'ix_users_activation_token' in _indexes('users'):
        op.drop_index(op.f('ix_users_activation_token'), table_name='users')
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               nullable=False)
    user_columns = _columns('users')
    if 'token_expires_at' in user_columns:
        op.drop_column('users', 'token_expires_at')
    if 'activation_token' in user_columns:
        op.drop_column('users', 'activation_token')
    if 'system_settings_key_key' not in _unique_constraints('system_settings'):
        op.create_unique_constraint('system_settings_key_key', 'system_settings', ['key'])
    op.alter_column('job_offers', 'languages',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('job_offers', 'soft_skills',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('interviews', 'status',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('evaluations', 'recommendation',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
